// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import { resolveDatabaseUrl } from "./src/lib/env/database-url";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Falls back to NETLIFY_DATABASE_URL if DATABASE_URL isn't set — see
    // src/lib/env/database-url.ts. Relative import (not "@/"): this file is
    // loaded by the Prisma CLI directly, outside the Next.js app bundle.
    url: resolveDatabaseUrl(),
  },
});
